### ISSUE TITLE
접속한 유저 firebase 연동

### ISSUE THREAD

**Issue by lolWK** [lolWK/ddingddong-game#11]
# 설명
익명 로그인한 유저를 firebase와 연동 시킵니다.

# Todo
- [x] firebase 익명 로그인 설정
- [x] 접속된 유저 db에 기본 정보 추가
- [x] 접속이 끊겼을 시 db에 유저 정보 삭제

# 기타
