### ISSUE TITLE
플레이어 준비 상태 체크

### ISSUE THREAD

**Issue by gunoc** [lolWK/ddingddong-game#27]
# 설명
모든 플레이어의 준비 상태를 확인하고 시작 준비를 마칩니다 

# Todo
- [ ] 준비 상태 만들기
- [ ] 모든 플레이어의 준비를 확인하고 시작 버튼 활성화
- [ ] 점수판 왼쪽 화살표 초록색 이미지로 바꾸기
