### ISSUE TITLE
시작 버튼과 관련된 기능

### ISSUE THREAD

**Issue by lolWK** [lolWK/ddingddong-game#35]
# 설명
시작 버튼과 관련된 여러가지 기능들

# Todo
- [ ] 모든 유저의 준비가 완료되어야 시작을 누를 수 있음
- [ ] 시작 버튼 클릭 후 시작되면 타이머 기능
- [ ] 시작 버튼 클릭 후 시작되면 코인이 나타나야 함

# 기타
